// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/goals-layouts/CompactList.tsx": () => import("../components/mockups/goals-layouts/CompactList.tsx"),
  "./components/mockups/goals-layouts/DashboardGrid.tsx": () => import("../components/mockups/goals-layouts/DashboardGrid.tsx"),
  "./components/mockups/goals-layouts/ScoreHero.tsx": () => import("../components/mockups/goals-layouts/ScoreHero.tsx")
};
